version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - morningkids-network
    restart: unless-stopped

networks:
  morningkids-network:
    driver: bridge
