version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:80"    # Maps port 8000 on your machine to port 80 in the container
    volumes:
      - .:/var/www/html  # Maps your local project folder to the container
    networks:
      - morningkids-network
    restart: unless-stopped

networks:
  morningkids-network:
    driver: bridge
